---REM INSERTING into MSG_TYPE_MOP
INSERT INTO MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) VALUES ('Pacs_002',null,'--MOP--','N','006',null,null) 
INSERT INTO MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) VALUES ('Pacs_004',null,'--MOP--','N','005','--MOP--_PACS004_FORMAT',null) 
INSERT INTO MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) VALUES ('Head_001',null,'--MOP--','N','001',null,null) 
INSERT INTO MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) VALUES ('Pacs_008',null,'--MOP--','N','005','--MOP--_PACS008_FORMAT',null) 
