--REM INSERTING into MSG_TYPE_MOP
Insert into MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) values ('Head_001',null,'HKFast','N','001',null,null);
Insert into MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) values ('Pacs_002',null,'HKFast','N','006',null,null);
Insert into MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) values ('Pacs_004',null,'HKFast','N','005','HKFast_PACS004_FORMAT',null);
Insert into MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) values ('Pacs_008',null,'HKFast','N','005','HKFast_PACS008_FORMAT',null);

UPDATE MSG_TYPE_MOP
SET FORMAT_TYPE = 'NPP_PACS004_FORMAT'
WHERE MOP = 'HKFast' AND MSG_TYPE = 'Pacs_004'; 

UPDATE MSG_TYPE_MOP
SET FORMAT_TYPE = 'NPP_PACS008_FORMAT'
WHERE MOP = 'HKFast' AND MSG_TYPE = 'Pacs_008'; 

DROP INDEX IX_UID_PRODUCT ;
DROP INDEX IX_PROD_CODE ;
UPDATE MSG_TYPE_MOP
SET FORMAT_TYPE = 'NPP_PACS008_FORMAT'
WHERE MOP IN ('HKFast') AND FORMAT_TYPE = 'HKFast_PACS008_FORMAT';
