---REM INSERTING into VALUE_DATE_INFO
delete from VALUE_DATE_INFO where UID_VALUE_DATE_INFO = '--OFFICE--^--DEPARTMENT--ast_IP_OUT' 
delete from VALUE_DATE_INFO where UID_VALUE_DATE_INFO = '--OFFICE--^DEF' 
