---REM INSERTING into DEPARTMENT
Insert into DEPARTMENT (DEPARTMENTCODE,DESCRIPTION,NCC,OFFICE,ALLOW_REROUTE,REC_STATUS,PROFILE_CHANGE_STATUS,PENDING_ACTION,EFFECTIVE_DATE,RANGE_LIST,TIME_STAMP,UID_DEPARTMENT) values ('--DEPARTMENT--','--MOP-- Department',null,'--OFFICE--',0,'AC','NO','CR',to_date('18-AUG-15','DD-MON-RR'),null,'2016-02-09 01:08:58.361','--DEPARTMENT--');
