---REM INSERTING into MSG_TYPE_MOP
Insert into MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) values ('Pacs_002',null,'--MOP--','N','006',null,null);
Insert into MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) values ('Pacs_004',null,'--MOP--','N','005','--MOP--_PACS004_FORMAT',null);
Insert into MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) values ('Head_001',null,'--MOP--','N','001',null,null);
Insert into MSG_TYPE_MOP (MSG_TYPE,MSG_SUB_TYPE,MOP,GUI_DISPLAY,VERSION_NM,FORMAT_TYPE,MSG_CLASS) values ('Pacs_008',null,'--MOP--','N','005','--MOP--_PACS008_FORMAT',null);
